name: Yuemin Li
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title

kramdown:
  input:          GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1